### Random Number Generation

31. **Generate an array of 10 random integers between 1 and 100.**

In [1]:
import numpy as np

random_integers = np.random.randint(1, 101, size=10)
print("Array of 10 random integers between 1 and 100:")
print(random_integers)

Array of 10 random integers between 1 and 100:
[56 58 25 18  4 60 66 35 27 84]



32. **Create a random permutation of an array.**

In [2]:
array = np.array([1, 2, 3, 4, 5])
random_permutation = np.random.permutation(array)
print("\nRandom permutation of an array:")
print(random_permutation)


Random permutation of an array:
[2 4 3 1 5]


33. **Sample 5 random elements from an array without replacement.**

In [3]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
random_sample = np.random.choice(array, size=5, replace=False)
print("\nSample 5 random elements from an array without replacement:")
print(random_sample)


Sample 5 random elements from an array without replacement:
[ 6  2 10  3  5]


34. **Set a random seed and generate a random array.**

In [4]:
np.random.seed(42)
random_array = np.random.rand(5)
print("\nRandom array with seed set to 42:")
print(random_array)


Random array with seed set to 42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


35. **Generate a 2D array of random numbers from a normal distribution.**

In [5]:
normal_random_array = np.random.randn(3, 4)
print("\n2D array of random numbers from a normal distribution:")
print(normal_random_array)


2D array of random numbers from a normal distribution:
[[ 0.27904129  1.01051528 -0.58087813 -0.52516981]
 [-0.57138017 -0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606 -0.74240684]]


### File I/O

36. **Save a NumPy array to a text file.**

In [6]:
array_to_save = np.array([1, 2, 3, 4, 5])
np.savetxt('array.txt', array_to_save)
print("\nSaved array to 'array.txt'.")


Saved array to 'array.txt'.


37. **Load a NumPy array from a text file.**

In [7]:
loaded_array = np.loadtxt('array.txt')
print("\nLoaded array from 'array.txt':")
print(loaded_array)


Loaded array from 'array.txt':
[1. 2. 3. 4. 5.]



38. **Save a NumPy array to a binary file with .npy extension.**

In [8]:
np.save('array.npy', array_to_save)
print("\nSaved array to 'array.npy'.")


Saved array to 'array.npy'.


39. **Load a NumPy array from a binary file with .npy extension.**

In [9]:
loaded_array_npy = np.load('array.npy')
print("\nLoaded array from 'array.npy':")
print(loaded_array_npy)


Loaded array from 'array.npy':
[1 2 3 4 5]



40. **Save a 2D NumPy array to a CSV file.**

In [10]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('array_2d.csv', array_2d, delimiter=',')
print("\nSaved 2D array to 'array_2d.csv'.")


Saved 2D array to 'array_2d.csv'.


### Advanced Array Manipulation

41. **Rotate a 2D array by 90 degrees.**

In [11]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rotated_array = np.rot90(array_2d)
print("\n2D array rotated by 90 degrees:")
print(rotated_array)


2D array rotated by 90 degrees:
[[3 6 9]
 [2 5 8]
 [1 4 7]]


42. **Remove all rows in a 2D array that contain NaN values.**

In [12]:
array_with_nan = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])
cleaned_array = array_with_nan[~np.isnan(array_with_nan).any(axis=1)]
print("\n2D array with rows containing NaN values removed:")
print(cleaned_array)


2D array with rows containing NaN values removed:
[[1. 2. 3.]
 [7. 8. 9.]]


43. **Replace NaN values in a NumPy array with the mean of that array.**

In [13]:
array_with_nan = np.array([1, 2, np.nan, 4, 5])
nan_mask = np.isnan(array_with_nan)
array_with_nan[nan_mask] = np.nanmean(array_with_nan)
print("\nArray with NaN values replaced with the mean of the array:")
print(array_with_nan)


Array with NaN values replaced with the mean of the array:
[1. 2. 3. 4. 5.]


44. **Find the unique elements in an array and return their counts.**

In [14]:
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_elements, counts = np.unique(array, return_counts=True)
print("\nUnique elements and their counts in the array:")
print("Elements:", unique_elements)
print("Counts:", counts)


Unique elements and their counts in the array:
Elements: [1 2 3 4]
Counts: [1 2 3 4]


45. **Compute the inverse of a matrix.**




```python

```


```python

```


```python

```


```python

```


```python
matrix = np.array([[1, 2], [3, 4]])
matrix_inverse = np.linalg.inv(matrix)
print("\nInverse of the matrix:")
print(matrix_inverse)
```

You can copy and run these code snippets in a Python environment to see the results. Make sure you have NumPy installed (`pip install numpy`) and note that file I/O operations will create files in your current working directory.