### Array Creation and Attributes

1. **Create a 1D array of numbers from 0 to 9.**

In [1]:
import numpy as np

# Solution
array_1d = np.arange(10)
print("1D array from 0 to 9:", array_1d)

1D array from 0 to 9: [0 1 2 3 4 5 6 7 8 9]


2. **Create a 2D array of shape (3, 3) with all elements as zeros.**

In [2]:
array_zeros = np.zeros((3, 3))
print("2D array of zeros (3x3):\n", array_zeros)

2D array of zeros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. **Create a 2D array of shape (3, 3) with all elements as ones.**

In [3]:
array_ones = np.ones((3, 3))
print("2D array of ones (3x3):\n", array_ones)

2D array of ones (3x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. **Create a 3x3 identity matrix.**

In [4]:
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



5. **Create an array of 10 random numbers between 0 and 1.**

In [5]:
random_array = np.random.rand(10)
print("Array of 10 random numbers between 0 and 1:", random_array)

Array of 10 random numbers between 0 and 1: [0.19327293 0.49203766 0.29895788 0.29007927 0.74724025 0.91865238
 0.262862   0.04920872 0.1130399  0.2021638 ]


### Array Indexing and Slicing

6. **Extract all the odd numbers from an array.**

In [6]:
import numpy as np

# Create a sample array
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution: Extract odd numbers
odd_numbers = array[array % 2 != 0]
print("Odd numbers in the array:", odd_numbers)

Odd numbers in the array: [1 3 5 7 9]


7. **Replace all odd numbers in an array with -1.**

In [7]:
# Create a sample array
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution: Replace odd numbers with -1
array[array % 2 != 0] = -1
print("Array after replacing odd numbers with -1:", array)

Array after replacing odd numbers with -1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


8. **Reverse an array.**

In [8]:
# Create a sample array
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution: Reverse the array
reversed_array = array[::-1]
print("Reversed array:", reversed_array)

Reversed array: [9 8 7 6 5 4 3 2 1 0]



9. **Select all rows of a 2D array where the first column is greater than 0.5.**

In [9]:
# Create a sample 2D array
array_2d = np.array([[0.2, 1.5, 2.3],
                     [0.6, 0.4, 0.8],
                     [0.9, 1.2, 0.5]])

# Solution: Select rows where the first column is greater than 0.5
selected_rows = array_2d[array_2d[:, 0] > 0.5]
print("Rows where the first column is greater than 0.5:\n", selected_rows)

Rows where the first column is greater than 0.5:
 [[0.6 0.4 0.8]
 [0.9 1.2 0.5]]


10. **Select elements from an array that are greater than the mean of the array.**

In [10]:
# Create a sample array
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution: Select elements greater than the mean
mean_value = array.mean()
elements_greater_than_mean = array[array > mean_value]
print("Elements greater than the mean:", elements_greater_than_mean)

Elements greater than the mean: [5 6 7 8 9]


### Array Manipulation

11. **Reshape a 1D array of size 9 into a 3x3 matrix.**

In [11]:
import numpy as np

# Create a 1D array of size 9
array_1d = np.arange(9)

# Solution: Reshape the 1D array into a 3x3 matrix
matrix_3x3 = array_1d.reshape((3, 3))
print("Reshaped 3x3 matrix:\n", matrix_3x3)

Reshaped 3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


12. **Flatten a 2D array into a 1D array.**

In [12]:
# Create a sample 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Solution: Flatten the 2D array into a 1D array
array_1d_flattened = array_2d.flatten()
print("Flattened 1D array:", array_1d_flattened)

Flattened 1D array: [1 2 3 4 5 6 7 8 9]


13. **Concatenate two arrays along the second axis.**

In [13]:
# Create two sample 2D arrays
array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])

# Solution: Concatenate the two arrays along the second axis (axis=1)
concatenated_array = np.concatenate((array_1, array_2), axis=1)
print("Concatenated array along the second axis:\n", concatenated_array)

Concatenated array along the second axis:
 [[1 2 5 6]
 [3 4 7 8]]


14. **Stack two arrays vertically.**

In [14]:
array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])

# Solution: Stack the two arrays vertically
stacked_array = np.vstack((array_1, array_2))
print("Stacked array vertically:\n", stacked_array)

Stacked array vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


15. **Split an array into three equal parts.**

In [15]:
# Create a sample array of size 9
array = np.arange(9)

# Solution: Split the array into three equal parts
split_arrays = np.array_split(array, 3)
print("Split array into three equal parts:")
for part in split_arrays:
    print(part)

Split array into three equal parts:
[0 1 2]
[3 4 5]
[6 7 8]
