### Mathematical Operations



In [3]:
import numpy as np
# Example arrays/matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])
array1d = np.array([1, 2, 3])
array2d = np.array([[1, 2, 3], [4, 5, 6]])

16. **Add two matrices element-wise.**

In [4]:
def add_matrices(matrix1, matrix2):
    return np.add(matrix1, matrix2)
print("Add two matrices element-wise:")
print(add_matrices(matrix1, matrix2))

Add two matrices element-wise:
[[ 8 10 12]
 [14 16 18]]


17. **Multiply two matrices element-wise.**

In [5]:
def multiply_matrices(matrix1, matrix2):
    return np.multiply(matrix1, matrix2)
print("\nMultiply two matrices element-wise:")
print(multiply_matrices(matrix1, matrix2))


Multiply two matrices element-wise:
[[ 7 16 27]
 [40 55 72]]


18. **Compute the dot product of two arrays.**

In [7]:
def dot_product(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

print("\nCompute the dot product of two arrays:")
print(dot_product(array1d, array1d))


Compute the dot product of two arrays:
14


19. **Compute the element-wise square root of an array.**

In [9]:
def square_root_array(array):
    return np.sqrt(array)

print("\nCompute the element-wise square root of an array:")
print(square_root_array(array1d))


Compute the element-wise square root of an array:
[1.         1.41421356 1.73205081]


20. **Compute the cumulative sum of an array.**

In [10]:
def cumulative_sum_array(array):
    return np.cumsum(array)

print("\nCompute the cumulative sum of an array:")
print(cumulative_sum_array(array1d))


Compute the cumulative sum of an array:
[1 3 6]


### Statistical Functions

21. **Find the mean of a 1D array.**

In [12]:
def mean_array(array):
    return np.mean(array)

print("\nFind the mean of a 1D array:")
print(mean_array(array1d))


Find the mean of a 1D array:
2.0


22. **Find the standard deviation of a 1D array.**

In [14]:
def std_dev_array(array):
    return np.std(array)

print("\nFind the standard deviation of a 1D array:")
print(std_dev_array(array1d))


Find the standard deviation of a 1D array:
0.816496580927726


23. **Find the median of a 1D array.**

In [15]:
def median_array(array):
    return np.median(array)

print("\nFind the median of a 1D array:")
print(median_array(array1d))


Find the median of a 1D array:
2.0



24. **Find the sum of each row in a 2D array.**


In [16]:
def sum_each_row(matrix):
    return np.sum(matrix, axis=1)

print("\nFind the sum of each row in a 2D array:")
print(sum_each_row(matrix1))


Find the sum of each row in a 2D array:
[ 6 15]


25. **Find the maximum element in a 1D array and its index.**

In [18]:
def max_element_index(array):
    max_index = np.argmax(array)
    return array[max_index], max_index

print("\nFind the maximum element in a 1D array and its index:")
max_elem, max_index = max_element_index(array1d)
print("Max element:", max_elem)
print("Index of max element:", max_index)


Find the maximum element in a 1D array and its index:
Max element: 3
Index of max element: 2


### Broadcasting and Vectorization

26. **Subtract the mean of each row of a 2D array.**

In [19]:
def subtract_mean_row(matrix):
    row_means = np.mean(matrix, axis=1, keepdims=True)
    return matrix - row_means

print("\nSubtract the mean of each row of a 2D array:")
print(subtract_mean_row(matrix1))


Subtract the mean of each row of a 2D array:
[[-1.  0.  1.]
 [-1.  0.  1.]]


27. **Normalize a 2D array to have values between 0 and 1.**

In [20]:
def normalize_array(matrix):
    return (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("\nNormalize a 2D array to have values between 0 and 1:")
print(normalize_array(array2d))


Normalize a 2D array to have values between 0 and 1:
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


28. **Add a 1D array to each row of a 2D array.**

In [22]:
def add_1d_array_to_rows(matrix, array):
    return matrix + array[:, np.newaxis]

print("\nAdd a 1D array to each row of a 2D array:")
print(add_1d_array_to_rows(matrix1, array1d))


Add a 1D array to each row of a 2D array:


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

29. **Multiply a 2D array by a 1D array element-wise.**

In [24]:
def multiply_2d_array_by_1d(matrix, array):
    return matrix * array[:, np.newaxis]

print("\nMultiply a 2D array by a 1D array element-wise:")
print(multiply_2d_array_by_1d(matrix1, array1d))


Multiply a 2D array by a 1D array element-wise:


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

30. **Compute the Euclidean distance between two arrays.**

In [25]:
def euclidean_distance(array1, array2):
    return np.linalg.norm(array1 - array2)

print("\nCompute the Euclidean distance between two arrays:")
print(euclidean_distance(array1d, array2d[0]))


Compute the Euclidean distance between two arrays:
0.0
